// react-with-redux/src/components/ProductPaginator.jsx
import { useSelector, useDispatch } from 'react-redux'

import { filterActions, productActions } from '../store'

export default function ProductPaginator(props) {

  const filter = useSelector(state => state.filterReducer)
  const products = useSelector(state => state.productsReducer)
  const dispatch = useDispatch()

  const prevPage = () => {
    dispatch(filterActions.setPage(filter.page - 1))
    dispatch(productActions.queryProducts(filter.query, filter.page - 1))
  }

  const nextPage = () => {
    dispatch(filterActions.setPage(filter.page + 1))
    dispatch(productActions.queryProducts(filter.query, filter.page + 1))
  }

  return <div>
    <button disabled={filter.page < 2} onClick={prevPage}>prev</button>
    <span>{filter.page}</span>
    <button disabled={products.list.length < products.pageSize} onClick={nextPage}>next</button>
  </div>
}

// vue-without-pinia/src/components/ProductPaginator.vue
<template>
  <div>
    <button
      :disabled="props.page < 2"
      @click="(e) => $emit('onPage', props.page - 1)"
    >
      prev
    </button>
    <span>{{ props.page }}</span>
    <button
      :disabled="props.products.length < props.pageSize"
      @click="(e) => $emit('onPage', props.page + 1)"
    >
      next
    </button>
  </div>
</template>

<script setup>
import { defineProps } from "vue";

const props = defineProps(["page", "products", "pageSize"]);
</script>

<style></style>
